# src/config/settings.yaml
spark:
  app_name: "Order Analysis"

paths:
  clientes: "./data-engineering-pyspark/data/input/dataset-json-clientes/data/clientes.json.gz"
  pedidos: "./data-engineering-pyspark/data/input/datasets-csv-pedidos/data/pedidos/"
  # pedidos : "./PATH-INVALIDO/data/input/datasets-csv-pedidos/data/pedidos" ## TESTE PATH INVALIDO
  output: "./data-engineering-pyspark/data/output/pedidos_por_cliente"

file_options:
  pedidos_csv:
    compression: "gzip"
    header: True
    sep: ";"

# Configuração Padrão de Mercado para Logging
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: default
      filename: "./data-engineering-pyspark/src/logs/dataeng-pyspark-poo.log"

  root:
    # O nível do root deve ser o menor (mais detalhado) dos handlers para não filtrar mensagens precocemente
    level: INFO
    handlers: [console, file]
    